// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc8yhFP2sdsAH-jOYnvuDnDz2HNjTTTlE',
    appId: '1:139399214689:web:ad3c50c399db29292b5c20',
    messagingSenderId: '139399214689',
    projectId: 'suri-d1c3c',
    authDomain: 'suri-d1c3c.firebaseapp.com',
    storageBucket: 'suri-d1c3c.appspot.com',
    measurementId: 'G-6D6VFE7MXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApdn-pydoXmlNNaBP-weVHKlCHbLhf8AU',
    appId: '1:139399214689:android:6b2716f65aed947f2b5c20',
    messagingSenderId: '139399214689',
    projectId: 'suri-d1c3c',
    storageBucket: 'suri-d1c3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv-_fccNMLcVyk2xqinq4jX28r4_TOmMI',
    appId: '1:139399214689:ios:65a0f7baa24946932b5c20',
    messagingSenderId: '139399214689',
    projectId: 'suri-d1c3c',
    storageBucket: 'suri-d1c3c.appspot.com',
    iosClientId: '139399214689-82vubtvk584gln9aeuk86k8seu4pc6lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.image',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv-_fccNMLcVyk2xqinq4jX28r4_TOmMI',
    appId: '1:139399214689:ios:65a0f7baa24946932b5c20',
    messagingSenderId: '139399214689',
    projectId: 'suri-d1c3c',
    storageBucket: 'suri-d1c3c.appspot.com',
    iosClientId: '139399214689-82vubtvk584gln9aeuk86k8seu4pc6lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.image',
  );
}
